apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.labelselector }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
      - name: petclinic-container
        image: {{ .Values.deployment.Imagename }}:latest
        command: ["sleep", "250"]
        resources:
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        ports:
        - containerPort: {{ .Values.deployment.targetport }}